// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openAPI

import (
	"time"
)

// AddScheduleResponse defines model for AddScheduleResponse.
type AddScheduleResponse struct {
	Id *int64 `json:"id,omitempty"`
}

// GetSchedulesResponse defines model for GetSchedulesResponse.
type GetSchedulesResponse struct {
	SchedulesId *[]int64 `json:"schedules_id,omitempty"`
}

// Medicine defines model for Medicine.
type Medicine struct {
	Date              *time.Time `json:"date,omitempty"`
	Id                *int64     `json:"id,omitempty"`
	Name              string     `json:"name"`
	Schedule          *[]string  `json:"schedule,omitempty"`
	TakingDuration    int32      `json:"taking_duration"`
	TreatmentDuration int32      `json:"treatment_duration"`
	UserId            int64      `json:"user_id"`
}

// NextTaking defines model for NextTaking.
type NextTaking struct {
	Name *string `json:"name,omitempty"`
	Time *string `json:"time,omitempty"`
}

// GetNextTakingsParams defines parameters for GetNextTakings.
type GetNextTakingsParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// GetScheduleParams defines parameters for GetSchedule.
type GetScheduleParams struct {
	ScheduleId int64 `form:"schedule_id" json:"schedule_id"`
	UserId     int64 `form:"user_id" json:"user_id"`
}

// GetSchedulesParams defines parameters for GetSchedules.
type GetSchedulesParams struct {
	UserId int64 `form:"user_id" json:"user_id"`
}

// PostScheduleJSONRequestBody defines body for PostSchedule for application/json ContentType.
type PostScheduleJSONRequestBody = Medicine
