openapi: 3.0.1
info:
  title: Medicine Schedule API
  description: API for managing medicine schedules and tracking next takings
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server
tags:
  - name: Schedules
    description: Operations with medicine schedules
  - name: Next Takings
    description: Operations to get next medicine takings

paths:
  /schedule:
    post:
      tags: [Schedules]
      summary: Add a new medicine schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Medicine'
      responses:
        '200':
          description: Schedule added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddScheduleResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
    get:
      tags: [ Schedules ]
      summary: Get schedule details
      parameters:
        - name: schedule_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Schedule details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Medicine'
        '400':
          description: Missing or invalid parameters
        '404':
          description: Schedule not found
        '500':
          description: Internal server error

  /schedules:
    get:
      tags: [Schedules]
      summary: Get all schedule IDs for a user
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: List of schedule IDs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSchedulesResponse'
        '400':
          description: Missing or invalid user_id parameter
        '500':
          description: Internal server error

  /next_takings:
    get:
      tags: [Next Takings]
      summary: Get next medicine takings within the time period
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: List of next takings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NextTaking'
        '400':
          description: Missing or invalid user_id parameter
        '404':
          description: No takings found
        '500':
          description: Internal server error

components:
  schemas:
    Medicine:
      type: object
      required:
        - name
        - taking_duration
        - treatment_duration
        - user_id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        taking_duration:
          type: integer
          format: int32
          minimum: 1
        treatment_duration:
          type: integer
          format: int32
          minimum: 1
        user_id:
          type: integer
          format: int64
          minimum: 1
        schedule:
          type: array
          items:
            type: string
        date:
          type: string
          format: date-time

    AddScheduleResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64

    GetSchedulesResponse:
      type: object
      properties:
        schedules_id:
          type: array
          items:
            type: integer
            format: int64

    NextTaking:
      type: object
      properties:
        name:
          type: string
        time:
          type: string